// Automatically generated from Google Fonts Noto Emoji Animation metadata.
class AnimatedEmoji {
  final String char;
  final String codepoint;
  final String name;
  final String category;

  const AnimatedEmoji({
    required this.char,
    required this.codepoint,
    required this.name,
    required this.category,
  });

  String get lottieUrl =>
      'https://fonts.gstatic.com/s/e/notoemoji/latest/$codepoint/lottie.json';
}

const List<String> animatedEmojiCategories = [
  'Smileys',
  'People',
  'Animals',
  'Food',
  'Travel',
  'Activities',
  'Objects',
  'Symbols',
  'Flags'
];

const List<AnimatedEmoji> animatedEmojis = [
  AnimatedEmoji(char: '😀', codepoint: '1f600', name: 'Smile', category: 'Smileys'),
  AnimatedEmoji(char: '😃', codepoint: '1f603', name: 'Smile With Big Eyes', category: 'Smileys'),
  AnimatedEmoji(char: '😄', codepoint: '1f604', name: 'Grin', category: 'Smileys'),
  AnimatedEmoji(char: '😁', codepoint: '1f601', name: 'Grinning', category: 'Smileys'),
  AnimatedEmoji(char: '😆', codepoint: '1f606', name: 'Laughing', category: 'Smileys'),
  AnimatedEmoji(char: '😅', codepoint: '1f605', name: 'Grin Sweat', category: 'Smileys'),
  AnimatedEmoji(char: '😂', codepoint: '1f602', name: 'Joy', category: 'Smileys'),
  AnimatedEmoji(char: '🤣', codepoint: '1f923', name: 'Rofl', category: 'Smileys'),
  AnimatedEmoji(char: '😭', codepoint: '1f62d', name: 'Loudly Crying', category: 'Smileys'),
  AnimatedEmoji(char: '😉', codepoint: '1f609', name: 'Wink', category: 'Smileys'),
  AnimatedEmoji(char: '😗', codepoint: '1f617', name: 'Kissing', category: 'Smileys'),
  AnimatedEmoji(char: '😙', codepoint: '1f619', name: 'Kissing Smiling Eyes', category: 'Smileys'),
  AnimatedEmoji(char: '😚', codepoint: '1f61a', name: 'Kissing Closed Eyes', category: 'Smileys'),
  AnimatedEmoji(char: '😘', codepoint: '1f618', name: 'Kissing Heart', category: 'Smileys'),
  AnimatedEmoji(char: '🥰', codepoint: '1f970', name: 'Heart Face', category: 'Smileys'),
  AnimatedEmoji(char: '😍', codepoint: '1f60d', name: 'Heart Eyes', category: 'Smileys'),
  AnimatedEmoji(char: '🤩', codepoint: '1f929', name: 'Star Struck', category: 'Smileys'),
  AnimatedEmoji(char: '🥳', codepoint: '1f973', name: 'Partying Face', category: 'Smileys'),
  AnimatedEmoji(char: '🫠', codepoint: '1fae0', name: 'Melting', category: 'Smileys'),
  AnimatedEmoji(char: '🙃', codepoint: '1f643', name: 'Upside Down Face', category: 'Smileys'),
  AnimatedEmoji(char: '🙂', codepoint: '1f642', name: 'Slightly Happy', category: 'Smileys'),
  AnimatedEmoji(char: '🥲', codepoint: '1f972', name: 'Happy Cry', category: 'Smileys'),
  AnimatedEmoji(char: '🥹', codepoint: '1f979', name: 'Holding Back Tears', category: 'Smileys'),
  AnimatedEmoji(char: '😊', codepoint: '1f60a', name: 'Blush', category: 'Smileys'),
  AnimatedEmoji(char: '☺️', codepoint: '263a_fe0f', name: 'Warm Smile', category: 'Smileys'),
  AnimatedEmoji(char: '😌', codepoint: '1f60c', name: 'Relieved', category: 'Smileys'),
  AnimatedEmoji(char: '🙂‍↕️', codepoint: '1f642_200d_2195_fe0f', name: 'Head Nod', category: 'Smileys'),
  AnimatedEmoji(char: '🙂‍↔️', codepoint: '1f642_200d_2194_fe0f', name: 'Head Shake', category: 'Smileys'),
  AnimatedEmoji(char: '😏', codepoint: '1f60f', name: 'Smirk', category: 'Smileys'),
  AnimatedEmoji(char: '🤤', codepoint: '1f924', name: 'Drool', category: 'Smileys'),
  AnimatedEmoji(char: '😋', codepoint: '1f60b', name: 'Yum', category: 'Smileys'),
  AnimatedEmoji(char: '😛', codepoint: '1f61b', name: 'Stuck Out Tongue', category: 'Smileys'),
  AnimatedEmoji(char: '😝', codepoint: '1f61d', name: 'Squinting Tongue', category: 'Smileys'),
  AnimatedEmoji(char: '😜', codepoint: '1f61c', name: 'Winky Tongue', category: 'Smileys'),
  AnimatedEmoji(char: '🤪', codepoint: '1f92a', name: 'Zany Face', category: 'Smileys'),
  AnimatedEmoji(char: '🫪', codepoint: '1faea', name: 'Distorted Face', category: 'Smileys'),
  AnimatedEmoji(char: '😔', codepoint: '1f614', name: 'Pensive', category: 'Smileys'),
  AnimatedEmoji(char: '🥺', codepoint: '1f97a', name: 'Pleading', category: 'Smileys'),
  AnimatedEmoji(char: '😬', codepoint: '1f62c', name: 'Grimacing', category: 'Smileys'),
  AnimatedEmoji(char: '😑', codepoint: '1f611', name: 'Expressionless', category: 'Smileys'),
  AnimatedEmoji(char: '😐', codepoint: '1f610', name: 'Neutral Face', category: 'Smileys'),
  AnimatedEmoji(char: '😶', codepoint: '1f636', name: 'Mouth None', category: 'Smileys'),
  AnimatedEmoji(char: '😶‍🌫️', codepoint: '1f636_200d_1f32b_fe0f', name: 'Face In Clouds', category: 'Smileys'),
  AnimatedEmoji(char: '🫥', codepoint: '1fae5', name: 'Dotted Line Face', category: 'Smileys'),
  AnimatedEmoji(char: '🤐', codepoint: '1f910', name: 'Zipper Face', category: 'Smileys'),
  AnimatedEmoji(char: '🫡', codepoint: '1fae1', name: 'Salute', category: 'Smileys'),
  AnimatedEmoji(char: '🤔', codepoint: '1f914', name: 'Thinking Face', category: 'Smileys'),
  AnimatedEmoji(char: '🤫', codepoint: '1f92b', name: 'Shushing Face', category: 'Smileys'),
  AnimatedEmoji(char: '🫢', codepoint: '1fae2', name: 'Hand Over Mouth', category: 'Smileys'),
  AnimatedEmoji(char: '🤭', codepoint: '1f92d', name: 'Smiling Eyes With Hand Over Mouth', category: 'Smileys'),
  AnimatedEmoji(char: '🥱', codepoint: '1f971', name: 'Yawn', category: 'Smileys'),
  AnimatedEmoji(char: '🤗', codepoint: '1f917', name: 'Hug Face', category: 'Smileys'),
  AnimatedEmoji(char: '🫣', codepoint: '1fae3', name: 'Peeking', category: 'Smileys'),
  AnimatedEmoji(char: '😱', codepoint: '1f631', name: 'Screaming', category: 'Smileys'),
  AnimatedEmoji(char: '🤨', codepoint: '1f928', name: 'Raised Eyebrow', category: 'Smileys'),
  AnimatedEmoji(char: '🧐', codepoint: '1f9d0', name: 'Monocle', category: 'Smileys'),
  AnimatedEmoji(char: '😒', codepoint: '1f612', name: 'Unamused', category: 'Smileys'),
  AnimatedEmoji(char: '🙄', codepoint: '1f644', name: 'Rolling Eyes', category: 'Smileys'),
  AnimatedEmoji(char: '😮‍💨', codepoint: '1f62e_200d_1f4a8', name: 'Exhale', category: 'Smileys'),
  AnimatedEmoji(char: '😤', codepoint: '1f624', name: 'Triumph', category: 'Smileys'),
  AnimatedEmoji(char: '😠', codepoint: '1f620', name: 'Angry', category: 'Smileys'),
  AnimatedEmoji(char: '😡', codepoint: '1f621', name: 'Rage', category: 'Smileys'),
  AnimatedEmoji(char: '🤬', codepoint: '1f92c', name: 'Cursing', category: 'Smileys'),
  AnimatedEmoji(char: '😞', codepoint: '1f61e', name: 'Sad', category: 'Smileys'),
  AnimatedEmoji(char: '😓', codepoint: '1f613', name: 'Sweat', category: 'Smileys'),
  AnimatedEmoji(char: '😟', codepoint: '1f61f', name: 'Worried', category: 'Smileys'),
  AnimatedEmoji(char: '😥', codepoint: '1f625', name: 'Concerned', category: 'Smileys'),
  AnimatedEmoji(char: '😢', codepoint: '1f622', name: 'Cry', category: 'Smileys'),
  AnimatedEmoji(char: '☹️', codepoint: '2639_fe0f', name: 'Big Frown', category: 'Smileys'),
  AnimatedEmoji(char: '🙁', codepoint: '1f641', name: 'Frown', category: 'Smileys'),
  AnimatedEmoji(char: '🫤', codepoint: '1fae4', name: 'Diagonal Mouth', category: 'Smileys'),
  AnimatedEmoji(char: '😕', codepoint: '1f615', name: 'Slightly Frowning', category: 'Smileys'),
  AnimatedEmoji(char: '😰', codepoint: '1f630', name: 'Anxious With Sweat', category: 'Smileys'),
  AnimatedEmoji(char: '😨', codepoint: '1f628', name: 'Scared', category: 'Smileys'),
  AnimatedEmoji(char: '😧', codepoint: '1f627', name: 'Anguished', category: 'Smileys'),
  AnimatedEmoji(char: '😦', codepoint: '1f626', name: 'Gasp', category: 'Smileys'),
  AnimatedEmoji(char: '😮', codepoint: '1f62e', name: 'Mouth Open', category: 'Smileys'),
  AnimatedEmoji(char: '😯', codepoint: '1f62f', name: 'Surprised', category: 'Smileys'),
  AnimatedEmoji(char: '😲', codepoint: '1f632', name: 'Astonished', category: 'Smileys'),
  AnimatedEmoji(char: '😳', codepoint: '1f633', name: 'Flushed', category: 'Smileys'),
  AnimatedEmoji(char: '🤯', codepoint: '1f92f', name: 'Mind Blown', category: 'Smileys'),
  AnimatedEmoji(char: '😖', codepoint: '1f616', name: 'Scrunched Mouth', category: 'Smileys'),
  AnimatedEmoji(char: '😣', codepoint: '1f623', name: 'Scrunched Eyes', category: 'Smileys'),
  AnimatedEmoji(char: '😩', codepoint: '1f629', name: 'Weary', category: 'Smileys'),
  AnimatedEmoji(char: '😫', codepoint: '1f62b', name: 'Distraught', category: 'Smileys'),
  AnimatedEmoji(char: '😵', codepoint: '1f635', name: 'X Eyes', category: 'Smileys'),
  AnimatedEmoji(char: '😵‍💫', codepoint: '1f635_200d_1f4ab', name: 'Dizzy Face', category: 'Smileys'),
  AnimatedEmoji(char: '🫨', codepoint: '1fae8', name: 'Shaking Face', category: 'Smileys'),
  AnimatedEmoji(char: '🥴', codepoint: '1f974', name: 'Woozy', category: 'Smileys'),
  AnimatedEmoji(char: '🥵', codepoint: '1f975', name: 'Hot Face', category: 'Smileys'),
  AnimatedEmoji(char: '🥶', codepoint: '1f976', name: 'Cold Face', category: 'Smileys'),
  AnimatedEmoji(char: '🤢', codepoint: '1f922', name: 'Sick', category: 'Smileys'),
  AnimatedEmoji(char: '🤮', codepoint: '1f92e', name: 'Vomit', category: 'Smileys'),
  AnimatedEmoji(char: '🫩', codepoint: '1fae9', name: 'Tired', category: 'Smileys'),
  AnimatedEmoji(char: '😴', codepoint: '1f634', name: 'Sleep', category: 'Smileys'),
  AnimatedEmoji(char: '😪', codepoint: '1f62a', name: 'Sleepy', category: 'Smileys'),
  AnimatedEmoji(char: '🤧', codepoint: '1f927', name: 'Sneeze', category: 'Smileys'),
  AnimatedEmoji(char: '🤒', codepoint: '1f912', name: 'Thermometer Face', category: 'Smileys'),
  AnimatedEmoji(char: '🤕', codepoint: '1f915', name: 'Bandage Face', category: 'Smileys'),
  AnimatedEmoji(char: '😷', codepoint: '1f637', name: 'Mask', category: 'Smileys'),
  AnimatedEmoji(char: '🤥', codepoint: '1f925', name: 'Liar', category: 'Smileys'),
  AnimatedEmoji(char: '😇', codepoint: '1f607', name: 'Halo', category: 'Smileys'),
  AnimatedEmoji(char: '🤠', codepoint: '1f920', name: 'Cowboy', category: 'Smileys'),
  AnimatedEmoji(char: '🤑', codepoint: '1f911', name: 'Money Face', category: 'Smileys'),
  AnimatedEmoji(char: '🤓', codepoint: '1f913', name: 'Nerd Face', category: 'Smileys'),
  AnimatedEmoji(char: '😎', codepoint: '1f60e', name: 'Sunglasses Face', category: 'Smileys'),
  AnimatedEmoji(char: '🥸', codepoint: '1f978', name: 'Disguise', category: 'Smileys'),
  AnimatedEmoji(char: '🤡', codepoint: '1f921', name: 'Clown', category: 'Smileys'),
  AnimatedEmoji(char: '💩', codepoint: '1f4a9', name: 'Poop', category: 'Smileys'),
  AnimatedEmoji(char: '😈', codepoint: '1f608', name: 'Imp Smile', category: 'Smileys'),
  AnimatedEmoji(char: '👿', codepoint: '1f47f', name: 'Imp Frown', category: 'Smileys'),
  AnimatedEmoji(char: '👻', codepoint: '1f47b', name: 'Ghost', category: 'Smileys'),
  AnimatedEmoji(char: '💀', codepoint: '1f480', name: 'Skull', category: 'Smileys'),
  AnimatedEmoji(char: '🤖', codepoint: '1f916', name: 'Robot', category: 'Smileys'),
  AnimatedEmoji(char: '👹', codepoint: '1f479', name: 'Ogre', category: 'Smileys'),
  AnimatedEmoji(char: '☃️', codepoint: '2603_fe0f', name: 'Snowman With Snow', category: 'Smileys'),
  AnimatedEmoji(char: '⛄', codepoint: '26c4', name: 'Snowman', category: 'Smileys'),
  AnimatedEmoji(char: '👽', codepoint: '1f47d', name: 'Alien', category: 'Smileys'),
  AnimatedEmoji(char: '👾', codepoint: '1f47e', name: 'Alien Monster', category: 'Smileys'),
  AnimatedEmoji(char: '🌚', codepoint: '1f31a', name: 'Moon Face New', category: 'Smileys'),
  AnimatedEmoji(char: '🌝', codepoint: '1f31d', name: 'Moon Face Full', category: 'Smileys'),
  AnimatedEmoji(char: '🌞', codepoint: '1f31e', name: 'Sun With Face', category: 'Smileys'),
  AnimatedEmoji(char: '🌛', codepoint: '1f31b', name: 'Moon Face First Quarter', category: 'Smileys'),
  AnimatedEmoji(char: '🌜', codepoint: '1f31c', name: 'Moon Face Last Quarter', category: 'Smileys'),
  AnimatedEmoji(char: '😺', codepoint: '1f63a', name: 'Smiley Cat', category: 'Smileys'),
  AnimatedEmoji(char: '😸', codepoint: '1f638', name: 'Smile Cat', category: 'Smileys'),
  AnimatedEmoji(char: '😹', codepoint: '1f639', name: 'Joy Cat', category: 'Smileys'),
  AnimatedEmoji(char: '😻', codepoint: '1f63b', name: 'Heart Eyes Cat', category: 'Smileys'),
  AnimatedEmoji(char: '😼', codepoint: '1f63c', name: 'Smirk Cat', category: 'Smileys'),
  AnimatedEmoji(char: '😽', codepoint: '1f63d', name: 'Kissing Cat', category: 'Smileys'),
  AnimatedEmoji(char: '🙀', codepoint: '1f640', name: 'Scream Cat', category: 'Smileys'),
  AnimatedEmoji(char: '😿', codepoint: '1f63f', name: 'Crying Cat Face', category: 'Smileys'),
  AnimatedEmoji(char: '😾', codepoint: '1f63e', name: 'Pouting Cat', category: 'Smileys'),
  AnimatedEmoji(char: '🙈', codepoint: '1f648', name: 'See No Evil Monkey', category: 'Smileys'),
  AnimatedEmoji(char: '🙉', codepoint: '1f649', name: 'Hear No Evil Monkey', category: 'Smileys'),
  AnimatedEmoji(char: '🙊', codepoint: '1f64a', name: 'Speak No Evil Monkey', category: 'Smileys'),
  AnimatedEmoji(char: '⭐', codepoint: '2b50', name: 'Star', category: 'Smileys'),
  AnimatedEmoji(char: '🌟', codepoint: '1f31f', name: 'Glowing Star', category: 'Smileys'),
  AnimatedEmoji(char: '✨', codepoint: '2728', name: 'Sparkles', category: 'Smileys'),
  AnimatedEmoji(char: '⚡', codepoint: '26a1', name: 'Electricity', category: 'Smileys'),
  AnimatedEmoji(char: '💥', codepoint: '1f4a5', name: 'Collision', category: 'Smileys'),
  AnimatedEmoji(char: '🫯', codepoint: '1faef', name: 'Fight', category: 'Smileys'),
  AnimatedEmoji(char: '🕳️', codepoint: '1f573_fe0f', name: 'Hole', category: 'Smileys'),
  AnimatedEmoji(char: '🔥', codepoint: '1f525', name: 'Fire', category: 'Smileys'),
  AnimatedEmoji(char: '💯', codepoint: '1f4af', name: '100', category: 'Smileys'),
  AnimatedEmoji(char: '🎉', codepoint: '1f389', name: 'Party Popper', category: 'Smileys'),
  AnimatedEmoji(char: '🎊', codepoint: '1f38a', name: 'Confetti Ball', category: 'Smileys'),
  AnimatedEmoji(char: '❤️', codepoint: '2764_fe0f', name: 'Red Heart', category: 'Smileys'),
  AnimatedEmoji(char: '🧡', codepoint: '1f9e1', name: 'Orange Heart', category: 'Smileys'),
  AnimatedEmoji(char: '💛', codepoint: '1f49b', name: 'Yellow Heart', category: 'Smileys'),
  AnimatedEmoji(char: '💚', codepoint: '1f49a', name: 'Green Heart', category: 'Smileys'),
  AnimatedEmoji(char: '🩵', codepoint: '1fa75', name: 'Light Blue Heart', category: 'Smileys'),
  AnimatedEmoji(char: '💙', codepoint: '1f499', name: 'Blue Heart', category: 'Smileys'),
  AnimatedEmoji(char: '💜', codepoint: '1f49c', name: 'Purple Heart', category: 'Smileys'),
  AnimatedEmoji(char: '🤎', codepoint: '1f90e', name: 'Brown Heart', category: 'Smileys'),
  AnimatedEmoji(char: '🖤', codepoint: '1f5a4', name: 'Black Heart', category: 'Smileys'),
  AnimatedEmoji(char: '🩶', codepoint: '1fa76', name: 'Grey Heart', category: 'Smileys'),
  AnimatedEmoji(char: '🤍', codepoint: '1f90d', name: 'White Heart', category: 'Smileys'),
  AnimatedEmoji(char: '🩷', codepoint: '1fa77', name: 'Pink Heart', category: 'Smileys'),
  AnimatedEmoji(char: '💘', codepoint: '1f498', name: 'Cupid', category: 'Smileys'),
  AnimatedEmoji(char: '💝', codepoint: '1f49d', name: 'Gift Heart', category: 'Smileys'),
  AnimatedEmoji(char: '💖', codepoint: '1f496', name: 'Sparkling Heart', category: 'Smileys'),
  AnimatedEmoji(char: '💗', codepoint: '1f497', name: 'Heart Grow', category: 'Smileys'),
  AnimatedEmoji(char: '💓', codepoint: '1f493', name: 'Beating Heart', category: 'Smileys'),
  AnimatedEmoji(char: '💞', codepoint: '1f49e', name: 'Revolving Hearts', category: 'Smileys'),
  AnimatedEmoji(char: '💕', codepoint: '1f495', name: 'Two Hearts', category: 'Smileys'),
  AnimatedEmoji(char: '💌', codepoint: '1f48c', name: 'Love Letter', category: 'Smileys'),
  AnimatedEmoji(char: '💟', codepoint: '1f49f', name: 'Heart Box', category: 'Smileys'),
  AnimatedEmoji(char: '♥️', codepoint: '2665_fe0f', name: 'Heart', category: 'Smileys'),
  AnimatedEmoji(char: '❣️', codepoint: '2763_fe0f', name: 'Heart Exclamation Point', category: 'Smileys'),
  AnimatedEmoji(char: '❤️‍🩹', codepoint: '2764_fe0f_200d_1fa79', name: 'Bandaged Heart', category: 'Smileys'),
  AnimatedEmoji(char: '💔', codepoint: '1f494', name: 'Broken Heart', category: 'Smileys'),
  AnimatedEmoji(char: '❤️‍🔥', codepoint: '2764_fe0f_200d_1f525', name: 'Fire Heart', category: 'Smileys'),
  AnimatedEmoji(char: '💋', codepoint: '1f48b', name: 'Kiss', category: 'Smileys'),
  AnimatedEmoji(char: '🫂', codepoint: '1fac2', name: 'Hugging', category: 'Smileys'),
  AnimatedEmoji(char: '🗣️', codepoint: '1f5e3_fe0f', name: 'Speaking Head', category: 'Smileys'),
  AnimatedEmoji(char: '👣', codepoint: '1f463', name: 'Footprints', category: 'Smileys'),
  AnimatedEmoji(char: '🫆', codepoint: '1fac6', name: 'Fingerprint', category: 'Smileys'),
  AnimatedEmoji(char: '🧠', codepoint: '1f9e0', name: 'Brain', category: 'Smileys'),
  AnimatedEmoji(char: '🫀', codepoint: '1fac0', name: 'Anatomical Heart', category: 'Smileys'),
  AnimatedEmoji(char: '🩸', codepoint: '1fa78', name: 'Blood', category: 'Smileys'),
  AnimatedEmoji(char: '🦠', codepoint: '1f9a0', name: 'Microbe', category: 'Smileys'),
  AnimatedEmoji(char: '🦴', codepoint: '1f9b4', name: 'Bone', category: 'Smileys'),
  AnimatedEmoji(char: '👀', codepoint: '1f440', name: 'Eyes', category: 'Smileys'),
  AnimatedEmoji(char: '👁️', codepoint: '1f441_fe0f', name: 'Eye', category: 'Smileys'),
  AnimatedEmoji(char: '🫦', codepoint: '1fae6', name: 'Biting Lip', category: 'Smileys'),
  AnimatedEmoji(char: '👃', codepoint: '1f443', name: 'Nose', category: 'Smileys'),
  AnimatedEmoji(char: '👂', codepoint: '1f442', name: 'Ear', category: 'Smileys'),
  AnimatedEmoji(char: '🦻', codepoint: '1f9bb', name: 'Hearing Aid', category: 'Smileys'),
  AnimatedEmoji(char: '🦶', codepoint: '1f9b6', name: 'Foot', category: 'Smileys'),
  AnimatedEmoji(char: '🦵', codepoint: '1f9b5', name: 'Leg', category: 'Smileys'),
  AnimatedEmoji(char: '🦿', codepoint: '1f9bf', name: 'Leg Mechanical', category: 'Smileys'),
  AnimatedEmoji(char: '🦾', codepoint: '1f9be', name: 'Arm Mechanical', category: 'Smileys'),
  AnimatedEmoji(char: '💪', codepoint: '1f4aa', name: 'Muscle', category: 'Smileys'),
  AnimatedEmoji(char: '👏', codepoint: '1f44f', name: 'Clap', category: 'Smileys'),
  AnimatedEmoji(char: '👍', codepoint: '1f44d', name: 'Thumbs Up', category: 'Smileys'),
  AnimatedEmoji(char: '👎', codepoint: '1f44e', name: 'Thumbs Down', category: 'Smileys'),
  AnimatedEmoji(char: '🫶', codepoint: '1faf6', name: 'Heart Hands', category: 'Smileys'),
  AnimatedEmoji(char: '🙌', codepoint: '1f64c', name: 'Raising Hands', category: 'Smileys'),
  AnimatedEmoji(char: '👐', codepoint: '1f450', name: 'Open Hands', category: 'Smileys'),
  AnimatedEmoji(char: '🤲', codepoint: '1f932', name: 'Palms Up', category: 'Smileys'),
  AnimatedEmoji(char: '🤜', codepoint: '1f91c', name: 'Fist Rightwards', category: 'Smileys'),
  AnimatedEmoji(char: '🤛', codepoint: '1f91b', name: 'Fist Leftwards', category: 'Smileys'),
  AnimatedEmoji(char: '✊', codepoint: '270a', name: 'Raised Fist', category: 'Smileys'),
  AnimatedEmoji(char: '👊', codepoint: '1f44a', name: 'Fist', category: 'Smileys'),
  AnimatedEmoji(char: '🫳', codepoint: '1faf3', name: 'Palm Down', category: 'Smileys'),
  AnimatedEmoji(char: '🫴', codepoint: '1faf4', name: 'Palm Up', category: 'Smileys'),
  AnimatedEmoji(char: '🫱', codepoint: '1faf1', name: 'Rightwards Hand', category: 'Smileys'),
  AnimatedEmoji(char: '🫲', codepoint: '1faf2', name: 'Leftwards Hand', category: 'Smileys'),
  AnimatedEmoji(char: '🫸', codepoint: '1faf8', name: 'Push Rightwards', category: 'Smileys'),
  AnimatedEmoji(char: '🫷', codepoint: '1faf7', name: 'Push Leftwards', category: 'Smileys'),
  AnimatedEmoji(char: '👋', codepoint: '1f44b', name: 'Wave', category: 'Smileys'),
  AnimatedEmoji(char: '🤚', codepoint: '1f91a', name: 'Back Hand', category: 'Smileys'),
  AnimatedEmoji(char: '🖐️', codepoint: '1f590_fe0f', name: 'Palm', category: 'Smileys'),
  AnimatedEmoji(char: '✋', codepoint: '270b', name: 'Raised Hand', category: 'Smileys'),
  AnimatedEmoji(char: '🖖', codepoint: '1f596', name: 'Vulcan', category: 'Smileys'),
  AnimatedEmoji(char: '🤟', codepoint: '1f91f', name: 'Love You Gesture', category: 'Smileys'),
  AnimatedEmoji(char: '🤘', codepoint: '1f918', name: 'Metal', category: 'Smileys'),
  AnimatedEmoji(char: '✌️', codepoint: '270c_fe0f', name: 'V', category: 'Smileys'),
  AnimatedEmoji(char: '🤞', codepoint: '1f91e', name: 'Crossed Fingers', category: 'Smileys'),
  AnimatedEmoji(char: '🫰', codepoint: '1faf0', name: 'Hand With Index Finger And Thumb Crossed', category: 'Smileys'),
  AnimatedEmoji(char: '🤙', codepoint: '1f919', name: 'Call Me Hand', category: 'Smileys'),
  AnimatedEmoji(char: '🤌', codepoint: '1f90c', name: 'Pinched Fingers', category: 'Smileys'),
  AnimatedEmoji(char: '🤏', codepoint: '1f90f', name: 'Pinch', category: 'Smileys'),
  AnimatedEmoji(char: '👌', codepoint: '1f44c', name: 'Ok', category: 'Smileys'),
  AnimatedEmoji(char: '🫵', codepoint: '1faf5', name: 'Pointing', category: 'Smileys'),
  AnimatedEmoji(char: '👉', codepoint: '1f449', name: 'Point Right', category: 'Smileys'),
  AnimatedEmoji(char: '👈', codepoint: '1f448', name: 'Point Left', category: 'Smileys'),
  AnimatedEmoji(char: '☝️', codepoint: '261d_fe0f', name: 'Index Finger', category: 'Smileys'),
  AnimatedEmoji(char: '👆', codepoint: '1f446', name: 'Point Up', category: 'Smileys'),
  AnimatedEmoji(char: '👇', codepoint: '1f447', name: 'Point Down', category: 'Smileys'),
  AnimatedEmoji(char: '🖕', codepoint: '1f595', name: 'Middle Finger', category: 'Smileys'),
  AnimatedEmoji(char: '✍️', codepoint: '270d_fe0f', name: 'Writing Hand', category: 'Smileys'),
  AnimatedEmoji(char: '🤳', codepoint: '1f933', name: 'Selfie', category: 'Smileys'),
  AnimatedEmoji(char: '🙏', codepoint: '1f64f', name: 'Folded Hands', category: 'Smileys'),
  AnimatedEmoji(char: '💅', codepoint: '1f485', name: 'Nail Care', category: 'Smileys'),
  AnimatedEmoji(char: '🤝', codepoint: '1f91d', name: 'Handshake', category: 'Smileys'),
  AnimatedEmoji(char: '🪂', codepoint: '1fa82', name: 'Parachute', category: 'People'),
  AnimatedEmoji(char: '🫈', codepoint: '1fac8', name: 'Hairy Creature', category: 'People'),
  AnimatedEmoji(char: '💃', codepoint: '1f483', name: 'Dancer Woman', category: 'People'),
  AnimatedEmoji(char: '💐', codepoint: '1f490', name: 'Bouquet', category: 'Animals'),
  AnimatedEmoji(char: '🌹', codepoint: '1f339', name: 'Rose', category: 'Animals'),
  AnimatedEmoji(char: '🥀', codepoint: '1f940', name: 'Wilted Flower', category: 'Animals'),
  AnimatedEmoji(char: '🌷', codepoint: '1f337', name: 'Tulip', category: 'Animals'),
  AnimatedEmoji(char: '🪷', codepoint: '1fab7', name: 'Lotus', category: 'Animals'),
  AnimatedEmoji(char: '🌸', codepoint: '1f338', name: 'Cherry Blossom', category: 'Animals'),
  AnimatedEmoji(char: '🪻', codepoint: '1fabb', name: 'Hyacinth', category: 'Animals'),
  AnimatedEmoji(char: '🌼', codepoint: '1f33c', name: 'Blossom', category: 'Animals'),
  AnimatedEmoji(char: '🍂', codepoint: '1f342', name: 'Fallen Leaf', category: 'Animals'),
  AnimatedEmoji(char: '🍁', codepoint: '1f341', name: 'Maple Leaf', category: 'Animals'),
  AnimatedEmoji(char: '🍄', codepoint: '1f344', name: 'Mushroom', category: 'Animals'),
  AnimatedEmoji(char: '🌿', codepoint: '1f33f', name: 'Herb', category: 'Animals'),
  AnimatedEmoji(char: '🌱', codepoint: '1f331', name: 'Plant', category: 'Animals'),
  AnimatedEmoji(char: '🍃', codepoint: '1f343', name: 'Leaves', category: 'Animals'),
  AnimatedEmoji(char: '🍀', codepoint: '1f340', name: 'Luck', category: 'Animals'),
  AnimatedEmoji(char: '🌵', codepoint: '1f335', name: 'Cactus', category: 'Animals'),
  AnimatedEmoji(char: '🪾', codepoint: '1fabe', name: 'Leafless Tree', category: 'Animals'),
  AnimatedEmoji(char: '🌲', codepoint: '1f332', name: 'Evergreen Tree', category: 'Animals'),
  AnimatedEmoji(char: '🪨', codepoint: '1faa8', name: 'Rock', category: 'Animals'),
  AnimatedEmoji(char: '🛘', codepoint: '1f6d8', name: 'Debris', category: 'Animals'),
  AnimatedEmoji(char: '🔥', codepoint: '1f525', name: 'Fire', category: 'Animals'),
  AnimatedEmoji(char: '🌋', codepoint: '1f30b', name: 'Volcano', category: 'Animals'),
  AnimatedEmoji(char: '🏞️', codepoint: '1f3de_fe0f', name: 'National Park', category: 'Animals'),
  AnimatedEmoji(char: '🌅', codepoint: '1f305', name: 'Sunrise', category: 'Animals'),
  AnimatedEmoji(char: '🌄', codepoint: '1f304', name: 'Sunrise Over Mountains', category: 'Animals'),
  AnimatedEmoji(char: '🌊', codepoint: '1f30a', name: 'Ocean', category: 'Animals'),
  AnimatedEmoji(char: '🌬️', codepoint: '1f32c_fe0f', name: 'Wind Face', category: 'Animals'),
  AnimatedEmoji(char: '❄️', codepoint: '2744_fe0f', name: 'Snowflake', category: 'Animals'),
  AnimatedEmoji(char: '🌀', codepoint: '1f300', name: 'Cyclone', category: 'Animals'),
  AnimatedEmoji(char: '🌪️', codepoint: '1f32a_fe0f', name: 'Tornado', category: 'Animals'),
  AnimatedEmoji(char: '⚡', codepoint: '26a1', name: 'Electricity', category: 'Animals'),
  AnimatedEmoji(char: '🌈', codepoint: '1f308', name: 'Rainbow', category: 'Animals'),
  AnimatedEmoji(char: '💧', codepoint: '1f4a7', name: 'Droplet', category: 'Animals'),
  AnimatedEmoji(char: '☁️', codepoint: '2601_fe0f', name: 'Cloud', category: 'Animals'),
  AnimatedEmoji(char: '🌧️', codepoint: '1f327_fe0f', name: 'Rain Cloud', category: 'Animals'),
  AnimatedEmoji(char: '🌩️', codepoint: '1f329_fe0f', name: 'Cloud With Lightning', category: 'Animals'),
  AnimatedEmoji(char: '⛅', codepoint: '26c5', name: 'Partly Sunny', category: 'Animals'),
  AnimatedEmoji(char: '🌞', codepoint: '1f31e', name: 'Sun With Face', category: 'Animals'),
  AnimatedEmoji(char: '🌟', codepoint: '1f31f', name: 'Glowing Star', category: 'Animals'),
  AnimatedEmoji(char: '🪐', codepoint: '1fa90', name: 'Ringed Planet', category: 'Animals'),
  AnimatedEmoji(char: '🌍', codepoint: '1f30d', name: 'Globe Showing Europe Africa', category: 'Animals'),
  AnimatedEmoji(char: '🌎', codepoint: '1f30e', name: 'Globe Showing Americas', category: 'Animals'),
  AnimatedEmoji(char: '🌏', codepoint: '1f30f', name: 'Globe Showing Asia Australia', category: 'Animals'),
  AnimatedEmoji(char: '🌌', codepoint: '1f30c', name: 'Milky Way', category: 'Animals'),
  AnimatedEmoji(char: '☄️', codepoint: '2604_fe0f', name: 'Comet', category: 'Animals'),
  AnimatedEmoji(char: '🙈', codepoint: '1f648', name: 'See No Evil Monkey', category: 'Animals'),
  AnimatedEmoji(char: '🙉', codepoint: '1f649', name: 'Hear No Evil Monkey', category: 'Animals'),
  AnimatedEmoji(char: '🙊', codepoint: '1f64a', name: 'Speak No Evil Monkey', category: 'Animals'),
  AnimatedEmoji(char: '🦁', codepoint: '1f981', name: 'Lion Face', category: 'Animals'),
  AnimatedEmoji(char: '🐺', codepoint: '1f43a', name: 'Wolf', category: 'Animals'),
  AnimatedEmoji(char: '🐻', codepoint: '1f43b', name: 'Bear Face', category: 'Animals'),
  AnimatedEmoji(char: '🐼', codepoint: '1f43c', name: 'Panda', category: 'Animals'),
  AnimatedEmoji(char: '🦊', codepoint: '1f98a', name: 'Fox Face', category: 'Animals'),
  AnimatedEmoji(char: '🐮', codepoint: '1f42e', name: 'Cow Face', category: 'Animals'),
  AnimatedEmoji(char: '🦄', codepoint: '1f984', name: 'Unicorn', category: 'Animals'),
  AnimatedEmoji(char: '🦎', codepoint: '1f98e', name: 'Lizard', category: 'Animals'),
  AnimatedEmoji(char: '🐉', codepoint: '1f409', name: 'Dragon', category: 'Animals'),
  AnimatedEmoji(char: '🦖', codepoint: '1f996', name: 'T Rex', category: 'Animals'),
  AnimatedEmoji(char: '🦕', codepoint: '1f995', name: 'Dinosaur', category: 'Animals'),
  AnimatedEmoji(char: '🐢', codepoint: '1f422', name: 'Turtle', category: 'Animals'),
  AnimatedEmoji(char: '🐊', codepoint: '1f40a', name: 'Crocodile', category: 'Animals'),
  AnimatedEmoji(char: '🐍', codepoint: '1f40d', name: 'Snake', category: 'Animals'),
  AnimatedEmoji(char: '🐸', codepoint: '1f438', name: 'Frog', category: 'Animals'),
  AnimatedEmoji(char: '🐇', codepoint: '1f407', name: 'Rabbit', category: 'Animals'),
  AnimatedEmoji(char: '🐀', codepoint: '1f400', name: 'Rat', category: 'Animals'),
  AnimatedEmoji(char: '🐩', codepoint: '1f429', name: 'Poodle', category: 'Animals'),
  AnimatedEmoji(char: '🐕', codepoint: '1f415', name: 'Dog', category: 'Animals'),
  AnimatedEmoji(char: '🦮', codepoint: '1f9ae', name: 'Guide Dog', category: 'Animals'),
  AnimatedEmoji(char: '🐕‍🦺', codepoint: '1f415_200d_1f9ba', name: 'Service Dog', category: 'Animals'),
  AnimatedEmoji(char: '🐖', codepoint: '1f416', name: 'Pig', category: 'Animals'),
  AnimatedEmoji(char: '🐎', codepoint: '1f40e', name: 'Racehorse', category: 'Animals'),
  AnimatedEmoji(char: '🫏', codepoint: '1facf', name: 'Donkey', category: 'Animals'),
  AnimatedEmoji(char: '🐂', codepoint: '1f402', name: 'Ox', category: 'Animals'),
  AnimatedEmoji(char: '🐐', codepoint: '1f410', name: 'Goat', category: 'Animals'),
  AnimatedEmoji(char: '🦥', codepoint: '1f9a5', name: 'Sloth', category: 'Animals'),
  AnimatedEmoji(char: '🦘', codepoint: '1f998', name: 'Kangaroo', category: 'Animals'),
  AnimatedEmoji(char: '🐅', codepoint: '1f405', name: 'Tiger', category: 'Animals'),
  AnimatedEmoji(char: '🐒', codepoint: '1f412', name: 'Monkey', category: 'Animals'),
  AnimatedEmoji(char: '🦍', codepoint: '1f98d', name: 'Gorilla', category: 'Animals'),
  AnimatedEmoji(char: '🦧', codepoint: '1f9a7', name: 'Orangutan', category: 'Animals'),
  AnimatedEmoji(char: '🐿️', codepoint: '1f43f_fe0f', name: 'Chipmunk', category: 'Animals'),
  AnimatedEmoji(char: '🦝', codepoint: '1f99d', name: 'Raccoon', category: 'Animals'),
  AnimatedEmoji(char: '🦔', codepoint: '1f994', name: 'Hedgehog', category: 'Animals'),
  AnimatedEmoji(char: '🦦', codepoint: '1f9a6', name: 'Otter', category: 'Animals'),
  AnimatedEmoji(char: '🦇', codepoint: '1f987', name: 'Bat', category: 'Animals'),
  AnimatedEmoji(char: '🐦', codepoint: '1f426', name: 'Bird', category: 'Animals'),
  AnimatedEmoji(char: '🐦‍⬛', codepoint: '1f426_200d_2b1b', name: 'Black Bird', category: 'Animals'),
  AnimatedEmoji(char: '🐓', codepoint: '1f413', name: 'Rooster', category: 'Animals'),
  AnimatedEmoji(char: '🐣', codepoint: '1f423', name: 'Hatching Chick', category: 'Animals'),
  AnimatedEmoji(char: '🐤', codepoint: '1f424', name: 'Baby Chick', category: 'Animals'),
  AnimatedEmoji(char: '🐥', codepoint: '1f425', name: 'Hatched Chick', category: 'Animals'),
  AnimatedEmoji(char: '🦅', codepoint: '1f985', name: 'Eagle', category: 'Animals'),
  AnimatedEmoji(char: '🦉', codepoint: '1f989', name: 'Owl', category: 'Animals'),
  AnimatedEmoji(char: '🕊️', codepoint: '1f54a_fe0f', name: 'Peace', category: 'Animals'),
  AnimatedEmoji(char: '🪿', codepoint: '1fabf', name: 'Goose', category: 'Animals'),
  AnimatedEmoji(char: '🦩', codepoint: '1f9a9', name: 'Flamingo', category: 'Animals'),
  AnimatedEmoji(char: '🦚', codepoint: '1f99a', name: 'Peacock', category: 'Animals'),
  AnimatedEmoji(char: '🐦‍🔥', codepoint: '1f426_200d_1f525', name: 'Phoenix', category: 'Animals'),
  AnimatedEmoji(char: '🐧', codepoint: '1f427', name: 'Penguin', category: 'Animals'),
  AnimatedEmoji(char: '🦭', codepoint: '1f9ad', name: 'Seal', category: 'Animals'),
  AnimatedEmoji(char: '🦈', codepoint: '1f988', name: 'Shark', category: 'Animals'),
  AnimatedEmoji(char: '🫍', codepoint: '1facd', name: 'Orca', category: 'Animals'),
  AnimatedEmoji(char: '🐬', codepoint: '1f42c', name: 'Dolphin', category: 'Animals'),
  AnimatedEmoji(char: '🐳', codepoint: '1f433', name: 'Whale', category: 'Animals'),
  AnimatedEmoji(char: '🐟', codepoint: '1f41f', name: 'Fish', category: 'Animals'),
  AnimatedEmoji(char: '🐡', codepoint: '1f421', name: 'Blowfish', category: 'Animals'),
  AnimatedEmoji(char: '🦞', codepoint: '1f99e', name: 'Lobster', category: 'Animals'),
  AnimatedEmoji(char: '🦀', codepoint: '1f980', name: 'Crab', category: 'Animals'),
  AnimatedEmoji(char: '🐙', codepoint: '1f419', name: 'Octopus', category: 'Animals'),
  AnimatedEmoji(char: '🪼', codepoint: '1fabc', name: 'Jellyfish', category: 'Animals'),
  AnimatedEmoji(char: '🫧', codepoint: '1fae7', name: 'Bubbles', category: 'Animals'),
  AnimatedEmoji(char: '🦂', codepoint: '1f982', name: 'Scorpion', category: 'Animals'),
  AnimatedEmoji(char: '🕷️', codepoint: '1f577_fe0f', name: 'Spider', category: 'Animals'),
  AnimatedEmoji(char: '🐌', codepoint: '1f40c', name: 'Snail', category: 'Animals'),
  AnimatedEmoji(char: '🐜', codepoint: '1f41c', name: 'Ant', category: 'Animals'),
  AnimatedEmoji(char: '🦗', codepoint: '1f997', name: 'Cricket', category: 'Animals'),
  AnimatedEmoji(char: '🦟', codepoint: '1f99f', name: 'Mosquito', category: 'Animals'),
  AnimatedEmoji(char: '🪳', codepoint: '1fab3', name: 'Cockroach', category: 'Animals'),
  AnimatedEmoji(char: '🪰', codepoint: '1fab0', name: 'Fly', category: 'Animals'),
  AnimatedEmoji(char: '🐝', codepoint: '1f41d', name: 'Bee', category: 'Animals'),
  AnimatedEmoji(char: '🐞', codepoint: '1f41e', name: 'Lady Bug', category: 'Animals'),
  AnimatedEmoji(char: '🦋', codepoint: '1f98b', name: 'Butterfly', category: 'Animals'),
  AnimatedEmoji(char: '🐛', codepoint: '1f41b', name: 'Bug', category: 'Animals'),
  AnimatedEmoji(char: '🪱', codepoint: '1fab1', name: 'Worm', category: 'Animals'),
  AnimatedEmoji(char: '🐾', codepoint: '1f43e', name: 'Paw Prints', category: 'Animals'),
  AnimatedEmoji(char: '🍓', codepoint: '1f353', name: 'Strawberry', category: 'Food'),
  AnimatedEmoji(char: '🍒', codepoint: '1f352', name: 'Cherries', category: 'Food'),
  AnimatedEmoji(char: '🍎', codepoint: '1f34e', name: 'Red Apple', category: 'Food'),
  AnimatedEmoji(char: '🍅', codepoint: '1f345', name: 'Tomato', category: 'Food'),
  AnimatedEmoji(char: '🍉', codepoint: '1f349', name: 'Watermelon', category: 'Food'),
  AnimatedEmoji(char: '🍊', codepoint: '1f34a', name: 'Tangerine', category: 'Food'),
  AnimatedEmoji(char: '🥕', codepoint: '1f955', name: 'Carrot', category: 'Food'),
  AnimatedEmoji(char: '🥭', codepoint: '1f96d', name: 'Mango', category: 'Food'),
  AnimatedEmoji(char: '🍍', codepoint: '1f34d', name: 'Pineapple', category: 'Food'),
  AnimatedEmoji(char: '🌽', codepoint: '1f33d', name: 'Ear Of Corn', category: 'Food'),
  AnimatedEmoji(char: '🍋', codepoint: '1f34b', name: 'Lemon', category: 'Food'),
  AnimatedEmoji(char: '🍈', codepoint: '1f348', name: 'Melon', category: 'Food'),
  AnimatedEmoji(char: '🍐', codepoint: '1f350', name: 'Pear', category: 'Food'),
  AnimatedEmoji(char: '🫛', codepoint: '1fadb', name: 'Pea Pod', category: 'Food'),
  AnimatedEmoji(char: '🥬', codepoint: '1f96c', name: 'Leafy Green', category: 'Food'),
  AnimatedEmoji(char: '🫑', codepoint: '1fad1', name: 'Bell Pepper', category: 'Food'),
  AnimatedEmoji(char: '🥝', codepoint: '1f95d', name: 'Kiwi Fruit', category: 'Food'),
  AnimatedEmoji(char: '🥑', codepoint: '1f951', name: 'Avocado', category: 'Food'),
  AnimatedEmoji(char: '🥦', codepoint: '1f966', name: 'Broccoli', category: 'Food'),
  AnimatedEmoji(char: '🥒', codepoint: '1f952', name: 'Cucumber', category: 'Food'),
  AnimatedEmoji(char: '🫐', codepoint: '1fad0', name: 'Blueberries', category: 'Food'),
  AnimatedEmoji(char: '🍇', codepoint: '1f347', name: 'Grapes', category: 'Food'),
  AnimatedEmoji(char: '🫜', codepoint: '1fadc', name: 'Root Vegetable', category: 'Food'),
  AnimatedEmoji(char: '🥔', codepoint: '1f954', name: 'Potato', category: 'Food'),
  AnimatedEmoji(char: '🧅', codepoint: '1f9c5', name: 'Onion', category: 'Food'),
  AnimatedEmoji(char: '🫚', codepoint: '1fada', name: 'Ginger', category: 'Food'),
  AnimatedEmoji(char: '🧄', codepoint: '1f9c4', name: 'Garlic', category: 'Food'),
  AnimatedEmoji(char: '🫘', codepoint: '1fad8', name: 'Beans', category: 'Food'),
  AnimatedEmoji(char: '🍞', codepoint: '1f35e', name: 'Bread', category: 'Food'),
  AnimatedEmoji(char: '🥞', codepoint: '1f95e', name: 'Pancakes', category: 'Food'),
  AnimatedEmoji(char: '🍳', codepoint: '1f373', name: 'Cooking', category: 'Food'),
  AnimatedEmoji(char: '🧀', codepoint: '1f9c0', name: 'Cheese Wedge', category: 'Food'),
  AnimatedEmoji(char: '🥓', codepoint: '1f953', name: 'Bacon', category: 'Food'),
  AnimatedEmoji(char: '🍗', codepoint: '1f357', name: 'Poultry Leg', category: 'Food'),
  AnimatedEmoji(char: '🍔', codepoint: '1f354', name: 'Hamburger', category: 'Food'),
  AnimatedEmoji(char: '🌭', codepoint: '1f32d', name: 'Hot Dog', category: 'Food'),
  AnimatedEmoji(char: '🥨', codepoint: '1f968', name: 'Pretzel', category: 'Food'),
  AnimatedEmoji(char: '🍕', codepoint: '1f355', name: 'Pizza', category: 'Food'),
  AnimatedEmoji(char: '🌮', codepoint: '1f32e', name: 'Taco', category: 'Food'),
  AnimatedEmoji(char: '🌯', codepoint: '1f32f', name: 'Burrito', category: 'Food'),
  AnimatedEmoji(char: '🍝', codepoint: '1f35d', name: 'Spaghetti', category: 'Food'),
  AnimatedEmoji(char: '🥗', codepoint: '1f957', name: 'Green Salad', category: 'Food'),
  AnimatedEmoji(char: '🍜', codepoint: '1f35c', name: 'Steaming Bowl', category: 'Food'),
  AnimatedEmoji(char: '🦞', codepoint: '1f99e', name: 'Lobster', category: 'Food'),
  AnimatedEmoji(char: '🍢', codepoint: '1f362', name: 'Oden', category: 'Food'),
  AnimatedEmoji(char: '🍡', codepoint: '1f361', name: 'Dango', category: 'Food'),
  AnimatedEmoji(char: '🍨', codepoint: '1f368', name: 'Ice Cream', category: 'Food'),
  AnimatedEmoji(char: '🍦', codepoint: '1f366', name: 'Soft Ice Cream', category: 'Food'),
  AnimatedEmoji(char: '🥧', codepoint: '1f967', name: 'Pie', category: 'Food'),
  AnimatedEmoji(char: '🍩', codepoint: '1f369', name: 'Doughnut', category: 'Food'),
  AnimatedEmoji(char: '🍪', codepoint: '1f36a', name: 'Cookie', category: 'Food'),
  AnimatedEmoji(char: '🧂', codepoint: '1f9c2', name: 'Salt', category: 'Food'),
  AnimatedEmoji(char: '🍿', codepoint: '1f37f', name: 'Popcorn', category: 'Food'),
  AnimatedEmoji(char: '🧋', codepoint: '1f9cb', name: 'Bubble Tea', category: 'Food'),
  AnimatedEmoji(char: '🧃', codepoint: '1f9c3', name: 'Beverage Box', category: 'Food'),
  AnimatedEmoji(char: '🍼', codepoint: '1f37c', name: 'Baby Bottle', category: 'Food'),
  AnimatedEmoji(char: '🍵', codepoint: '1f375', name: 'Teacup Without Handle', category: 'Food'),
  AnimatedEmoji(char: '☕', codepoint: '2615', name: 'Hot Beverage', category: 'Food'),
  AnimatedEmoji(char: '🫖', codepoint: '1fad6', name: 'Teapot', category: 'Food'),
  AnimatedEmoji(char: '🧉', codepoint: '1f9c9', name: 'Mate', category: 'Food'),
  AnimatedEmoji(char: '🍻', codepoint: '1f37b', name: 'Clinking Beer Mugs', category: 'Food'),
  AnimatedEmoji(char: '🥂', codepoint: '1f942', name: 'Clinking Glasses', category: 'Food'),
  AnimatedEmoji(char: '🍾', codepoint: '1f37e', name: 'Bottle With Popping Cork', category: 'Food'),
  AnimatedEmoji(char: '🍷', codepoint: '1f377', name: 'Wine Glass', category: 'Food'),
  AnimatedEmoji(char: '🫗', codepoint: '1fad7', name: 'Pour', category: 'Food'),
  AnimatedEmoji(char: '🍹', codepoint: '1f379', name: 'Tropical Drink', category: 'Food'),
  AnimatedEmoji(char: '🥢', codepoint: '1f962', name: 'Chopsticks', category: 'Food'),
  AnimatedEmoji(char: '🍽️', codepoint: '1f37d_fe0f', name: 'Fork And Knife With Plate', category: 'Food'),
  AnimatedEmoji(char: '🛑', codepoint: '1f6d1', name: 'Stop Sign', category: 'Travel'),
  AnimatedEmoji(char: '🚧', codepoint: '1f6a7', name: 'Construction', category: 'Travel'),
  AnimatedEmoji(char: '🚨', codepoint: '1f6a8', name: 'Police Car Light', category: 'Travel'),
  AnimatedEmoji(char: '⛽', codepoint: '26fd', name: 'Fuel Pump', category: 'Travel'),
  AnimatedEmoji(char: '🛟', codepoint: '1f6df', name: 'Ring Buoy', category: 'Travel'),
  AnimatedEmoji(char: '⚓', codepoint: '2693', name: 'Anchor', category: 'Travel'),
  AnimatedEmoji(char: '🚦', codepoint: '1f6a6', name: 'Vertical Traffic Light', category: 'Travel'),
  AnimatedEmoji(char: '🚲', codepoint: '1f6b2', name: 'Bicycle', category: 'Travel'),
  AnimatedEmoji(char: '🏍️', codepoint: '1f3cd_fe0f', name: 'Motorcycle', category: 'Travel'),
  AnimatedEmoji(char: '🚗', codepoint: '1f697', name: 'Automobile', category: 'Travel'),
  AnimatedEmoji(char: '🚚', codepoint: '1f69a', name: 'Delivery Truck', category: 'Travel'),
  AnimatedEmoji(char: '🚜', codepoint: '1f69c', name: 'Tractor', category: 'Travel'),
  AnimatedEmoji(char: '🏎️', codepoint: '1f3ce_fe0f', name: 'Racing Car', category: 'Travel'),
  AnimatedEmoji(char: '🚕', codepoint: '1f695', name: 'Taxi', category: 'Travel'),
  AnimatedEmoji(char: '🚌', codepoint: '1f68c', name: 'Bus', category: 'Travel'),
  AnimatedEmoji(char: '🚂', codepoint: '1f682', name: 'Locomotive', category: 'Travel'),
  AnimatedEmoji(char: '⛵', codepoint: '26f5', name: 'Sailboat', category: 'Travel'),
  AnimatedEmoji(char: '🛶', codepoint: '1f6f6', name: 'Canoe', category: 'Travel'),
  AnimatedEmoji(char: '🛸', codepoint: '1f6f8', name: 'Flying Saucer', category: 'Travel'),
  AnimatedEmoji(char: '🚀', codepoint: '1f680', name: 'Rocket', category: 'Travel'),
  AnimatedEmoji(char: '✈️', codepoint: '2708_fe0f', name: 'Airplane', category: 'Travel'),
  AnimatedEmoji(char: '🛫', codepoint: '1f6eb', name: 'Airplane Departure', category: 'Travel'),
  AnimatedEmoji(char: '🛬', codepoint: '1f6ec', name: 'Airplane Arrival', category: 'Travel'),
  AnimatedEmoji(char: '🎢', codepoint: '1f3a2', name: 'Roller Coaster', category: 'Travel'),
  AnimatedEmoji(char: '🎡', codepoint: '1f3a1', name: 'Ferris Wheel', category: 'Travel'),
  AnimatedEmoji(char: '🎠', codepoint: '1f3a0', name: 'Carousel Horse', category: 'Travel'),
  AnimatedEmoji(char: '🗿', codepoint: '1f5ff', name: 'Moai', category: 'Travel'),
  AnimatedEmoji(char: '🏚️', codepoint: '1f3da_fe0f', name: 'Derelict House', category: 'Travel'),
  AnimatedEmoji(char: '🏠', codepoint: '1f3e0', name: 'House', category: 'Travel'),
  AnimatedEmoji(char: '🏕️', codepoint: '1f3d5_fe0f', name: 'Camping', category: 'Travel'),
  AnimatedEmoji(char: '🌇', codepoint: '1f307', name: 'Sunset', category: 'Travel'),
  AnimatedEmoji(char: '🎉', codepoint: '1f389', name: 'Party Popper', category: 'Activities'),
  AnimatedEmoji(char: '🎊', codepoint: '1f38a', name: 'Confetti Ball', category: 'Activities'),
  AnimatedEmoji(char: '🎈', codepoint: '1f388', name: 'Balloon', category: 'Activities'),
  AnimatedEmoji(char: '🎂', codepoint: '1f382', name: 'Birthday Cake', category: 'Activities'),
  AnimatedEmoji(char: '🎁', codepoint: '1f381', name: 'Wrapped Gift', category: 'Activities'),
  AnimatedEmoji(char: '🎆', codepoint: '1f386', name: 'Fireworks', category: 'Activities'),
  AnimatedEmoji(char: '🪔', codepoint: '1fa94', name: 'Diya Lamp', category: 'Activities'),
  AnimatedEmoji(char: '🪅', codepoint: '1fa85', name: 'Piñata', category: 'Activities'),
  AnimatedEmoji(char: '🪩', codepoint: '1faa9', name: 'Mirror Ball', category: 'Activities'),
  AnimatedEmoji(char: '🥇', codepoint: '1f947', name: 'Gold Medal', category: 'Activities'),
  AnimatedEmoji(char: '🥈', codepoint: '1f948', name: 'Silver Medal', category: 'Activities'),
  AnimatedEmoji(char: '🥉', codepoint: '1f949', name: 'Bronze Medal', category: 'Activities'),
  AnimatedEmoji(char: '🏆', codepoint: '1f3c6', name: 'Trophy', category: 'Activities'),
  AnimatedEmoji(char: '⚽', codepoint: '26bd', name: 'Soccer Ball', category: 'Activities'),
  AnimatedEmoji(char: '⚾', codepoint: '26be', name: 'Baseball', category: 'Activities'),
  AnimatedEmoji(char: '🥎', codepoint: '1f94e', name: 'Softball', category: 'Activities'),
  AnimatedEmoji(char: '🏀', codepoint: '1f3c0', name: 'Basketball', category: 'Activities'),
  AnimatedEmoji(char: '🏉', codepoint: '1f3c9', name: 'Rugby Football', category: 'Activities'),
  AnimatedEmoji(char: '🎾', codepoint: '1f3be', name: 'Tennis', category: 'Activities'),
  AnimatedEmoji(char: '🏸', codepoint: '1f3f8', name: 'Badminton', category: 'Activities'),
  AnimatedEmoji(char: '🥍', codepoint: '1f94d', name: 'Lacrosse', category: 'Activities'),
  AnimatedEmoji(char: '🏏', codepoint: '1f3cf', name: 'Cricket Game', category: 'Activities'),
  AnimatedEmoji(char: '🏑', codepoint: '1f3d1', name: 'Field Hockey', category: 'Activities'),
  AnimatedEmoji(char: '🏒', codepoint: '1f3d2', name: 'Ice Hockey', category: 'Activities'),
  AnimatedEmoji(char: '🎿', codepoint: '1f3bf', name: 'Skis', category: 'Activities'),
  AnimatedEmoji(char: '⛸️', codepoint: '26f8_fe0f', name: 'Ice Skate', category: 'Activities'),
  AnimatedEmoji(char: '🛼', codepoint: '1f6fc', name: 'Roller Skates', category: 'Activities'),
  AnimatedEmoji(char: '🩰', codepoint: '1fa70', name: 'Ballet Shoes', category: 'Activities'),
  AnimatedEmoji(char: '🛹', codepoint: '1f6f9', name: 'Skateboard', category: 'Activities'),
  AnimatedEmoji(char: '⛳', codepoint: '26f3', name: 'Flag In Hole', category: 'Activities'),
  AnimatedEmoji(char: '🎯', codepoint: '1f3af', name: 'Direct Hit', category: 'Activities'),
  AnimatedEmoji(char: '🥏', codepoint: '1f94f', name: 'Flying Disc', category: 'Activities'),
  AnimatedEmoji(char: '🪃', codepoint: '1fa83', name: 'Boomerang', category: 'Activities'),
  AnimatedEmoji(char: '🪁', codepoint: '1fa81', name: 'Kite', category: 'Activities'),
  AnimatedEmoji(char: '🎣', codepoint: '1f3a3', name: 'Fishing Pole', category: 'Activities'),
  AnimatedEmoji(char: '🥋', codepoint: '1f94b', name: 'Martial Arts Uniform', category: 'Activities'),
  AnimatedEmoji(char: '🎱', codepoint: '1f3b1', name: '8 Ball', category: 'Activities'),
  AnimatedEmoji(char: '🏓', codepoint: '1f3d3', name: 'Ping Pong', category: 'Activities'),
  AnimatedEmoji(char: '🎳', codepoint: '1f3b3', name: 'Bowling', category: 'Activities'),
  AnimatedEmoji(char: '♟️', codepoint: '265f_fe0f', name: 'Chess Pawn', category: 'Activities'),
  AnimatedEmoji(char: '🎲', codepoint: '1f3b2', name: 'Die', category: 'Activities'),
  AnimatedEmoji(char: '🎰', codepoint: '1f3b0', name: 'Slot Machine', category: 'Activities'),
  AnimatedEmoji(char: '🪄', codepoint: '1fa84', name: 'Wand', category: 'Activities'),
  AnimatedEmoji(char: '📷', codepoint: '1f4f7', name: 'Camera', category: 'Activities'),
  AnimatedEmoji(char: '📸', codepoint: '1f4f8', name: 'Camera Flash', category: 'Activities'),
  AnimatedEmoji(char: '🫟', codepoint: '1fadf', name: 'Splatter', category: 'Activities'),
  AnimatedEmoji(char: '🎷', codepoint: '1f3b7', name: 'Saxophone', category: 'Activities'),
  AnimatedEmoji(char: '🎺', codepoint: '1f3ba', name: 'Trumpet', category: 'Activities'),
  AnimatedEmoji(char: '🪊', codepoint: '1fa8a', name: 'Trombone', category: 'Activities'),
  AnimatedEmoji(char: '🎸', codepoint: '1f3b8', name: 'Guitar', category: 'Activities'),
  AnimatedEmoji(char: '🪕', codepoint: '1fa95', name: 'Banjo', category: 'Activities'),
  AnimatedEmoji(char: '🎻', codepoint: '1f3bb', name: 'Violin', category: 'Activities'),
  AnimatedEmoji(char: '🪉', codepoint: '1fa89', name: 'Harp', category: 'Activities'),
  AnimatedEmoji(char: '🥁', codepoint: '1f941', name: 'Drum', category: 'Activities'),
  AnimatedEmoji(char: '🪇', codepoint: '1fa87', name: 'Maracas', category: 'Activities'),
  AnimatedEmoji(char: '📺', codepoint: '1f4fa', name: 'Television', category: 'Activities'),
  AnimatedEmoji(char: '🎞️', codepoint: '1f39e_fe0f', name: 'Film', category: 'Activities'),
  AnimatedEmoji(char: '🎬', codepoint: '1f3ac', name: 'Clapper', category: 'Activities'),
  AnimatedEmoji(char: '🎭', codepoint: '1f3ad', name: 'Performing Arts', category: 'Activities'),
  AnimatedEmoji(char: '🎟️', codepoint: '1f39f_fe0f', name: 'Admission Tickets', category: 'Activities'),
  AnimatedEmoji(char: '📟', codepoint: '1f4df', name: 'Pager', category: 'Objects'),
  AnimatedEmoji(char: '🔌', codepoint: '1f50c', name: 'Electric Plug', category: 'Objects'),
  AnimatedEmoji(char: '🔋', codepoint: '1f50b', name: 'Battery Full', category: 'Objects'),
  AnimatedEmoji(char: '🪫', codepoint: '1faab', name: 'Battery Low', category: 'Objects'),
  AnimatedEmoji(char: '💿', codepoint: '1f4bf', name: 'Optical Disk', category: 'Objects'),
  AnimatedEmoji(char: '💻', codepoint: '1f4bb', name: 'Laptop Computer', category: 'Objects'),
  AnimatedEmoji(char: '🖨️', codepoint: '1f5a8_fe0f', name: 'Printer', category: 'Objects'),
  AnimatedEmoji(char: '🪎', codepoint: '1fa8e', name: 'Treasure', category: 'Objects'),
  AnimatedEmoji(char: '🪙', codepoint: '1fa99', name: 'Coin', category: 'Objects'),
  AnimatedEmoji(char: '💎', codepoint: '1f48e', name: 'Gem Stone', category: 'Objects'),
  AnimatedEmoji(char: '💸', codepoint: '1f4b8', name: 'Money With Wings', category: 'Objects'),
  AnimatedEmoji(char: '⚖️', codepoint: '2696_fe0f', name: 'Balance Scale', category: 'Objects'),
  AnimatedEmoji(char: '🛒', codepoint: '1f6d2', name: 'Shopping Cart', category: 'Objects'),
  AnimatedEmoji(char: '💡', codepoint: '1f4a1', name: 'Light Bulb', category: 'Objects'),
  AnimatedEmoji(char: '🧹', codepoint: '1f9f9', name: 'Broom', category: 'Objects'),
  AnimatedEmoji(char: '🧦', codepoint: '1f9e6', name: 'Socks', category: 'Objects'),
  AnimatedEmoji(char: '🎓', codepoint: '1f393', name: 'Graduation Cap', category: 'Objects'),
  AnimatedEmoji(char: '👑', codepoint: '1f451', name: 'Crown', category: 'Objects'),
  AnimatedEmoji(char: '💍', codepoint: '1f48d', name: 'Ring', category: 'Objects'),
  AnimatedEmoji(char: '🪭', codepoint: '1faad', name: 'Fan', category: 'Objects'),
  AnimatedEmoji(char: '☂️', codepoint: '2602_fe0f', name: 'Umbrella', category: 'Objects'),
  AnimatedEmoji(char: '👠', codepoint: '1f460', name: 'High Heeled Shoe', category: 'Objects'),
  AnimatedEmoji(char: '👟', codepoint: '1f45f', name: 'Running Shoe', category: 'Objects'),
  AnimatedEmoji(char: '🌡️', codepoint: '1f321_fe0f', name: 'Thermometer', category: 'Objects'),
  AnimatedEmoji(char: '🩺', codepoint: '1fa7a', name: 'Stethoscope', category: 'Objects'),
  AnimatedEmoji(char: '🛠️', codepoint: '1f6e0_fe0f', name: 'Hammer And Wrench', category: 'Objects'),
  AnimatedEmoji(char: '🪏', codepoint: '1fa8f', name: 'Shovel', category: 'Objects'),
  AnimatedEmoji(char: '⚙️', codepoint: '2699_fe0f', name: 'Gear', category: 'Objects'),
  AnimatedEmoji(char: '⛓️‍💥', codepoint: '26d3_fe0f_200d_1f4a5', name: 'Broken Chain', category: 'Objects'),
  AnimatedEmoji(char: '⛓️', codepoint: '26d3_fe0f', name: 'Chains', category: 'Objects'),
  AnimatedEmoji(char: '🖇️', codepoint: '1f587_fe0f', name: 'Linked Paperclips', category: 'Objects'),
  AnimatedEmoji(char: '✂️', codepoint: '2702_fe0f', name: 'Scissors', category: 'Objects'),
  AnimatedEmoji(char: '✏️', codepoint: '270f_fe0f', name: 'Pencil', category: 'Objects'),
  AnimatedEmoji(char: '📚', codepoint: '1f4da', name: 'Books', category: 'Objects'),
  AnimatedEmoji(char: '📊', codepoint: '1f4ca', name: 'Bar Chart', category: 'Objects'),
  AnimatedEmoji(char: '📈', codepoint: '1f4c8', name: 'Chart Increasing', category: 'Objects'),
  AnimatedEmoji(char: '📉', codepoint: '1f4c9', name: 'Chart Decreasing', category: 'Objects'),
  AnimatedEmoji(char: '🗑️', codepoint: '1f5d1_fe0f', name: 'Wastebasket', category: 'Objects'),
  AnimatedEmoji(char: '📦', codepoint: '1f4e6', name: 'Package', category: 'Objects'),
  AnimatedEmoji(char: '🗳️', codepoint: '1f5f3_fe0f', name: 'Ballot Box', category: 'Objects'),
  AnimatedEmoji(char: '⏰', codepoint: '23f0', name: 'Alarm Clock', category: 'Objects'),
  AnimatedEmoji(char: '⌛', codepoint: '231b', name: 'Hourglass Done', category: 'Objects'),
  AnimatedEmoji(char: '⏳', codepoint: '23f3', name: 'Hourglass Not Done', category: 'Objects'),
  AnimatedEmoji(char: '🛎️', codepoint: '1f6ce_fe0f', name: 'Bellhop Bell', category: 'Objects'),
  AnimatedEmoji(char: '🔔', codepoint: '1f514', name: 'Bell', category: 'Objects'),
  AnimatedEmoji(char: '📣', codepoint: '1f4e3', name: 'Megaphone', category: 'Objects'),
  AnimatedEmoji(char: '🔎', codepoint: '1f50e', name: 'Magnifying Glass Tilted Right', category: 'Objects'),
  AnimatedEmoji(char: '🔮', codepoint: '1f52e', name: 'Crystal Ball', category: 'Objects'),
  AnimatedEmoji(char: '💣', codepoint: '1f4a3', name: 'Bomb', category: 'Objects'),
  AnimatedEmoji(char: '🪤', codepoint: '1faa4', name: 'Mouse Trap', category: 'Objects'),
  AnimatedEmoji(char: '🔒', codepoint: '1f512', name: 'Locked', category: 'Objects'),
  AnimatedEmoji(char: '❤️', codepoint: '2764_fe0f', name: 'Red Heart', category: 'Symbols'),
  AnimatedEmoji(char: '🧡', codepoint: '1f9e1', name: 'Orange Heart', category: 'Symbols'),
  AnimatedEmoji(char: '💛', codepoint: '1f49b', name: 'Yellow Heart', category: 'Symbols'),
  AnimatedEmoji(char: '💚', codepoint: '1f49a', name: 'Green Heart', category: 'Symbols'),
  AnimatedEmoji(char: '💙', codepoint: '1f499', name: 'Blue Heart', category: 'Symbols'),
  AnimatedEmoji(char: '💜', codepoint: '1f49c', name: 'Purple Heart', category: 'Symbols'),
  AnimatedEmoji(char: '🤎', codepoint: '1f90e', name: 'Brown Heart', category: 'Symbols'),
  AnimatedEmoji(char: '🖤', codepoint: '1f5a4', name: 'Black Heart', category: 'Symbols'),
  AnimatedEmoji(char: '🤍', codepoint: '1f90d', name: 'White Heart', category: 'Symbols'),
  AnimatedEmoji(char: '🩷', codepoint: '1fa77', name: 'Pink Heart', category: 'Symbols'),
  AnimatedEmoji(char: '🩵', codepoint: '1fa75', name: 'Light Blue Heart', category: 'Symbols'),
  AnimatedEmoji(char: '🩶', codepoint: '1fa76', name: 'Gray Heart', category: 'Symbols'),
  AnimatedEmoji(char: '♥️', codepoint: '2665_fe0f', name: 'Heart', category: 'Symbols'),
  AnimatedEmoji(char: '♠️', codepoint: '2660_fe0f', name: 'Spade', category: 'Symbols'),
  AnimatedEmoji(char: '♈', codepoint: '2648', name: 'Aries', category: 'Symbols'),
  AnimatedEmoji(char: '♉', codepoint: '2649', name: 'Taurus', category: 'Symbols'),
  AnimatedEmoji(char: '♊', codepoint: '264a', name: 'Gemini', category: 'Symbols'),
  AnimatedEmoji(char: '♋', codepoint: '264b', name: 'Cancer', category: 'Symbols'),
  AnimatedEmoji(char: '♌', codepoint: '264c', name: 'Leo', category: 'Symbols'),
  AnimatedEmoji(char: '♍', codepoint: '264d', name: 'Virgo', category: 'Symbols'),
  AnimatedEmoji(char: '♎', codepoint: '264e', name: 'Libra', category: 'Symbols'),
  AnimatedEmoji(char: '♏', codepoint: '264f', name: 'Scorpio', category: 'Symbols'),
  AnimatedEmoji(char: '♐', codepoint: '2650', name: 'Sagittarius', category: 'Symbols'),
  AnimatedEmoji(char: '♑', codepoint: '2651', name: 'Capricorn', category: 'Symbols'),
  AnimatedEmoji(char: '♒', codepoint: '2652', name: 'Aquarius', category: 'Symbols'),
  AnimatedEmoji(char: '♓', codepoint: '2653', name: 'Pisces', category: 'Symbols'),
  AnimatedEmoji(char: '⛎', codepoint: '26ce', name: 'Ophiuchus', category: 'Symbols'),
  AnimatedEmoji(char: '🗯️', codepoint: '1f5ef_fe0f', name: 'Anger Bubble', category: 'Symbols'),
  AnimatedEmoji(char: '💬', codepoint: '1f4ac', name: 'Speech Bubble', category: 'Symbols'),
  AnimatedEmoji(char: '❗', codepoint: '2757', name: 'Exclamation', category: 'Symbols'),
  AnimatedEmoji(char: '❓', codepoint: '2753', name: 'Question', category: 'Symbols'),
  AnimatedEmoji(char: '⁉️', codepoint: '2049_fe0f', name: 'Exclamation Question Mark', category: 'Symbols'),
  AnimatedEmoji(char: '‼️', codepoint: '203c_fe0f', name: 'Exclamation Double', category: 'Symbols'),
  AnimatedEmoji(char: '❌', codepoint: '274c', name: 'X', category: 'Symbols'),
  AnimatedEmoji(char: '🆘', codepoint: '1f198', name: 'Sos', category: 'Symbols'),
  AnimatedEmoji(char: '♨️', codepoint: '2668_fe0f', name: 'Hot Springs', category: 'Symbols'),
  AnimatedEmoji(char: '📴', codepoint: '1f4f4', name: 'Phone Off', category: 'Symbols'),
  AnimatedEmoji(char: '☢️', codepoint: '2622_fe0f', name: 'Radioactive', category: 'Symbols'),
  AnimatedEmoji(char: '☣️', codepoint: '2623_fe0f', name: 'Biohazard', category: 'Symbols'),
  AnimatedEmoji(char: '⚠️', codepoint: '26a0_fe0f', name: 'Warning', category: 'Symbols'),
  AnimatedEmoji(char: '✅', codepoint: '2705', name: 'Check Mark', category: 'Symbols'),
  AnimatedEmoji(char: '🆕', codepoint: '1f195', name: 'New', category: 'Symbols'),
  AnimatedEmoji(char: '🆓', codepoint: '1f193', name: 'Free', category: 'Symbols'),
  AnimatedEmoji(char: '🆙', codepoint: '1f199', name: 'Up!', category: 'Symbols'),
  AnimatedEmoji(char: '🆗', codepoint: '1f197', name: 'Ok Button', category: 'Symbols'),
  AnimatedEmoji(char: '🆒', codepoint: '1f192', name: 'Cool', category: 'Symbols'),
  AnimatedEmoji(char: '🚮', codepoint: '1f6ae', name: 'Litter', category: 'Symbols'),
  AnimatedEmoji(char: '☮️', codepoint: '262e_fe0f', name: 'Peace Symbol', category: 'Symbols'),
  AnimatedEmoji(char: '☯️', codepoint: '262f_fe0f', name: 'Yin Yang', category: 'Symbols'),
  AnimatedEmoji(char: '♾️', codepoint: '267e_fe0f', name: 'Infinity', category: 'Symbols'),
  AnimatedEmoji(char: '🎶', codepoint: '1f3b6', name: 'Musical Notes', category: 'Symbols'),
  AnimatedEmoji(char: '➕', codepoint: '2795', name: 'Plus Sign', category: 'Symbols'),
  AnimatedEmoji(char: '©️', codepoint: 'a9_fe0f', name: 'Copyright', category: 'Symbols'),
  AnimatedEmoji(char: '®️', codepoint: 'ae_fe0f', name: 'Registered', category: 'Symbols'),
  AnimatedEmoji(char: '™️', codepoint: '2122_fe0f', name: 'Trade Mark', category: 'Symbols'),
  AnimatedEmoji(char: '🏁', codepoint: '1f3c1', name: 'Chequered Flag', category: 'Flags'),
  AnimatedEmoji(char: '🚩', codepoint: '1f6a9', name: 'Triangular Flag', category: 'Flags'),
  AnimatedEmoji(char: '🏴', codepoint: '1f3f4', name: 'Black Flag', category: 'Flags'),
  AnimatedEmoji(char: '🏳️', codepoint: '1f3f3_fe0f', name: 'White Flag', category: 'Flags'),
];
