# socket.io event handlers — relay-only ephemeral messaging.
# messages never touch the DB. they go: sender → server relay → recipient(s).
# offline recipients get queued (encrypted) and drain on reconnect.

import json
import logging
import secrets
from datetime import datetime, timezone

import socketio
from sqlalchemy import select, update

from app.core.config import settings
from app.core.database import async_session_factory
from app.core.offline_queue import drain as drain_queue, enqueue as enqueue_message
from app.core.security import now_ms, verify_session_token
from app.models import ChatMember, User
from app.realtime.connection_manager import manager

logger = logging.getLogger("cryptalk.realtime")

_MAX_RELAY_BYTES = 65_536


def _auth_from_environ(environ: dict) -> str | None:
    from http.cookies import SimpleCookie
    cookie_header = environ.get("HTTP_COOKIE", "")
    if not cookie_header:
        return None
    jar = SimpleCookie()
    try:
        jar.load(cookie_header)
    except Exception:
        return None
    morsel = jar.get(settings.COOKIE_NAME)
    if not morsel:
        return None
    return verify_session_token(morsel.value)


def register_handlers(sio: socketio.AsyncServer) -> None:

    @sio.event
    async def connect(sid: str, environ: dict, auth: dict = None) -> bool | None:
        user_id = None
        if auth and isinstance(auth, dict):
            token = auth.get("token")
            if token:
                user_id = verify_session_token(token)

        if not user_id:
            user_id = _auth_from_environ(environ)

        if not user_id:
            logger.warning("Socket %s rejected: no valid session cookie or token", sid)
            await sio.emit("auth-error", {"message": "Not authenticated"}, to=sid)
            return False
        manager.add(sid, user_id)
        logger.info("Socket connected: %s (user: %s)", sid, user_id[:8])

        async with async_session_factory() as db:
            await db.execute(
                update(User)
                .where(User.id == user_id)
                .values(is_online=True, last_seen=now_ms())
            )
            await db.commit()
        await sio.emit("user-status", {"userId": user_id, "isOnline": True})

        await sio.emit(
            "presence",
            {"users": [{"userId": uid, "isOnline": True} for uid in manager.all_online_user_ids()]},
            to=sid,
        )

        # drain any queued messages from while this user was offline
        queued = drain_queue(user_id)
        if queued:
            await sio.emit("queued-messages", {"messages": queued}, to=sid)
            logger.info("Delivered %d queued messages to user %s", len(queued), user_id[:8])

        return True

    @sio.on("identify")
    async def on_identify(sid: str, data: dict) -> None:
        pass

    @sio.on("join-chat")
    async def on_join_chat(sid: str, data: dict) -> None:
        user_id = manager.get_user_id(sid)
        chat_id = data.get("chatId")
        if not user_id or not chat_id:
            return
        async with async_session_factory() as db:
            result = await db.execute(
                select(ChatMember).where(
                    ChatMember.chat_id == chat_id, ChatMember.user_id == user_id
                )
            )
            if not result.scalar_one_or_none():
                return
        await sio.enter_room(sid, f"chat:{chat_id}")
        logger.info("Socket %s (user %s) joined room chat:%s", sid, user_id[:8], chat_id)

    @sio.on("leave-chat")
    async def on_leave_chat(sid: str, data: dict) -> None:
        chat_id = data.get("chatId")
        if chat_id:
            await sio.leave_room(sid, f"chat:{chat_id}")

    @sio.on("send-message")
    async def on_send_message(sid: str, data: dict) -> None:
        user_id = manager.get_user_id(sid)
        if not user_id or not isinstance(data, dict):
            return
        chat_id = data.get("chatId")
        message = data.get("message")
        if not chat_id or not message or not isinstance(message, dict):
            return
        if len(json.dumps(data, default=str)) > _MAX_RELAY_BYTES:
            return

        # preserve existing ID/createdAt if already generated by sender client
        message["id"] = message.get("id") or secrets.token_hex(12)
        message["senderId"] = user_id
        message["createdAt"] = message.get("createdAt") or datetime.now(timezone.utc).isoformat()
        message["status"] = "sent"

        payload = {"chatId": chat_id, "message": message}

        # relay to everyone in the room except sender (if sender already added locally)
        await sio.emit("message", payload, room=f"chat:{chat_id}", skip_sid=sid)

        # ack back to sender
        await sio.emit("message-ack", {
            "chatId": chat_id,
            "messageId": message["id"],
            "createdAt": message["createdAt"],
        }, to=sid)

        # queue for offline members
        async with async_session_factory() as db:
            result = await db.execute(
                select(ChatMember.user_id).where(ChatMember.chat_id == chat_id)
            )
            all_member_ids = [row[0] for row in result.all()]

        for member_id in all_member_ids:
            if member_id == user_id:
                continue
            if not manager.get_sockets_for_user(member_id):
                enqueue_message(member_id, payload)

    @sio.on("typing")
    async def on_typing(sid: str, data: dict) -> None:
        user_id = manager.get_user_id(sid)
        if not user_id or not isinstance(data, dict):
            return
        chat_id = data.get("chatId")
        if not chat_id:
            return
        data["userId"] = user_id
        await sio.emit("typing", data, room=f"chat:{chat_id}", skip_sid=sid)

    @sio.on("message-status")
    async def on_message_status(sid: str, data: dict) -> None:
        user_id = manager.get_user_id(sid)
        if not user_id or not isinstance(data, dict):
            return
        chat_id = data.get("chatId")
        if not chat_id:
            return
        data["userId"] = user_id
        await sio.emit("message-status", data, room=f"chat:{chat_id}")

        # if this is a delivery confirmation for a file, trigger cleanup
        attachment_path = data.get("attachmentPath")
        if attachment_path and data.get("status") == "delivered":
            try:
                from app.core.storage import StorageService
                await StorageService.delete_file(attachment_path)
                logger.info("Auto-deleted delivered attachment: %s", attachment_path)
            except Exception as e:
                logger.warning("Failed to auto-delete attachment %s: %s", attachment_path, e)

    @sio.on("recording")
    async def on_recording(sid: str, data: dict) -> None:
        user_id = manager.get_user_id(sid)
        if not user_id or not isinstance(data, dict):
            return
        chat_id = data.get("chatId")
        if not chat_id:
            return
        data["userId"] = user_id
        await sio.emit("recording", data, room=f"chat:{chat_id}", skip_sid=sid)

    @sio.on("reaction")
    async def on_reaction(sid: str, data: dict) -> None:
        user_id = manager.get_user_id(sid)
        if not user_id or not isinstance(data, dict):
            return
        chat_id = data.get("chatId")
        if not chat_id:
            return
        data["userId"] = user_id
        await sio.emit("reaction", data, room=f"chat:{chat_id}")

    @sio.on("message-update")
    async def on_message_update(sid: str, data: dict) -> None:
        user_id = manager.get_user_id(sid)
        if not user_id or not isinstance(data, dict):
            return
        chat_id = data.get("chatId")
        if not chat_id:
            return
        if len(json.dumps(data, default=str)) > _MAX_RELAY_BYTES:
            return
        data["userId"] = user_id
        await sio.emit("message-update", data, room=f"chat:{chat_id}")

    @sio.on("chat-updated")
    async def on_chat_updated(sid: str, data: dict) -> None:
        user_id = manager.get_user_id(sid)
        if not user_id or not isinstance(data, dict):
            return
        chat = data.get("chat")
        member_ids = data.get("memberIds", [])
        if user_id not in member_ids:
            return
        for member_id in member_ids:
            for target_sid in manager.get_sockets_for_user(member_id):
                await sio.emit("chat-updated", {"chat": chat}, to=target_sid)

    @sio.event
    async def disconnect(sid: str) -> None:
        offline_user = manager.remove(sid)
        if offline_user:
            try:
                async with async_session_factory() as db:
                    await db.execute(
                        update(User)
                        .where(User.id == offline_user)
                        .values(is_online=False, last_seen=now_ms())
                    )
                    await db.commit()
                await sio.emit("user-status", {"userId": offline_user, "isOnline": False})
            except Exception as e:
                logger.error("Failed to mark user %s offline on disconnect: %s", offline_user, e)
        logger.info("Socket disconnected: %s", sid)
